language: node_js

node_js:
    - "stable"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

# after_success:
#     - npm run report-coveralls
#     - npm run report-codecov
